### ISSUE TITLE
Nintendo Switch port

### ISSUE THREAD

**Issue by usineur** [Sappharad/rvm_soniccd#1]
Hi,

I recently made a Nintendo Switch port of this engine: https://github.com/usineur/rvm_soniccd

Do not hesitate to comment actual changes here: https://github.com/Sappharad/rvm_soniccd/compare/master...usineur:switch

Note that most of the changes are "Switch only". They are two special changes in the following files:

- rvm/Core/AnimationSystem.c: I had to declare b3 var explicitly to "signed char".
- rvm/Core/FileIO.c: After the fclose, fileReader is explicitly set to NULL. It causes segfault on Switch or Linux without it.

This port also uses GLEW, but is not yet integrated in the devkitpro (Switch toolchain) packages env: https://github.com/devkitPro/pacman-packages/pull/204

**Comment by Sappharad** [comment]
Changes look good to me.

The only thing I'd say is remove/change the icon.jpg copied from the original game, don't want any original game data in the repository for legal reasons.
